### ISSUE TITLE
Need a way to listen to signals without `AddMatch` boilerplate

### ISSUE THREAD

**Issue by YurySolovyov** [LinkTed/dbus-async#1]
When I want to listen to signals on some known interface + path, I'd like to have a method that handles setting up match for me.
This could be a method that takes closure passing filtered messages, or one that takes a channel, like you do in examples.

**Comment by LinkTed** [comment]
Hi Yury,
I am planing to change the internals of the `dbus-aync` code, to make it more flexible. So, it would be possible to listen to signals by interface and path.

**Comment by LinkTed** [comment]
Sorry that it took so long. I added a filter closure in the `add_signal_hanlder` function in the  commit 7127d6f30913550122405422663712ae8cefcb77. Soon I will add some examples.

**Comment by YurySolovyov** [comment]
No rush, thanks for looking at this.

**Comment by LinkTed** [comment]
The new version [2.0.0](https://crates.io/crates/dbus-async) is published.
