### ISSUE TITLE
MatchRule::ArgPath cant be used with/as suffix

### ISSUE THREAD

**Issue by User65k** [LinkTed/dbus-async#4]
Hi, I am trying to add a Match for "org.freedesktop.DBus.ObjectManager.InterfacesAdded". These are always sent with path "/" in the header. However they contain the real path in the body.

Matching on a suffix like with `MatchRule::PathNamespace` is also possible for argXpath by ending the path with `/`.
However that is not possible with `MatchRule::ArgPath` as it takes an `ObjectPath` and will give an Error on parsing (`EndSlash`).

Would it make sense to add a `MatchRule::ArgPathNamespace` for this case?

I am currently using a workaround:
```rs
format!("{},arg0path='/org/bluez/'",MatchRule::encode(other_match_rules))
```

From [dbus.freedesktop.org](https://dbus.freedesktop.org/doc/api/html/group__DBusBus.html#ga4eb6401ba014da3dbe3dc4e2a8e5b3ef):

    If your argument match has a 'path' suffix (eg: "arg0path='/some/path/'") then it is considered a match if
    the argument exactly matches the given string or if one of them ends in a '/' and is a prefix of the other.

**Comment by LinkTed** [comment]
I think it is better to add  member to `ArgPath`, which define whether it is a namespace or not. But not in this repository [dbus-message-parser](https://github.com/LinkTed/dbus-message-parser).
